project1/project1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls', namespace='students')),
]

project1/students/urls.py
from django.urls import path

from . import views
from .views import create_student, update_student, delete_student, create_diagnostic, delete_diagnostic,update_diagnostic

app_name = 'students'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.create_student, name='create_student'),
    path('update/<int:student_id>/', views.update_student, name='update_student'),
    path('delete/<int:student_id>/', views.delete_student, name='delete_student'),
    path('<int:student_id>/ ', views.diagnostics, name='diagnostics'),
    path('<int:student_id>/new', views.create_diagnostic, name='create_diagnostic'),
    path('<int:student_id>/delete/<int:diagnostic_id>/', views.delete_diagnostic, name='delete_diagnostic'),
    path('<int:student_id>/update/<int:diagnostic_id>/', views.update_diagnostic, name='update_diagnostic'),
]

project1/students/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=50, blank=False)
    birth_date = models.DateField('birthday', blank=False)

    BOY = 'BOY'
    GIRL = 'GIRL'
    GENDER_CHOICES = (
        (BOY, 'Boy'),
        (GIRL, 'Girl'),
    )
    gender = models.CharField(
        max_length=5,
        choices=GENDER_CHOICES,
        default=BOY,
        blank=False,
    )

    current_school_name = models.CharField(max_length=50)

    KINDER1 = '幼末'
    KINDER2 = '幼小'
    KINDER3 = '幼中'
    KINDER4 = '幼大'
    PRIMARY1 = '小一'
    PRIMARY2 = '小二'
    YEAR_IN_SCHOOL_CHOICES = (
        (KINDER1, '幼末'),
        (KINDER2, '幼小'),
        (KINDER3, '幼中'),
        (KINDER4, '幼大'),
        (PRIMARY1, '小一'),
        (PRIMARY2, '小二'),
    )
    current_school_grade = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=KINDER1,
        blank=False,
    )

    name_en = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Diagnostic(models.Model):
    name = models.CharField(max_length=50, blank=False)
    test_datetime = models.DateTimeField('test_time', blank=False)


    MK = 'MK'
    MP1 = 'MP1'
    MP2 = 'MP2'
    MP3 = 'MP3'
    MP4 = 'MP4'
    TEST_LEVEL_CHOICES = (
        (MK, 'MK'),
        (MP1, 'MP1'),
        (MP2, 'MP2'),
        (MP3, 'MP3'),
        (MP4, 'MP4'),
    )
    test_level = models.CharField(
        max_length=3,
        choices=TEST_LEVEL_CHOICES,
        default=MK,
        blank=False,
    )


    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return self.test_level

project1/students/forms.py
from django import forms
from .models import Student, Diagnostic

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'birth_date', 'gender', 'current_school_name', 'current_school_grade', 'name_en']
        widgets = {
            'birth_date': forms.DateInput(attrs={'class': 'datetime-input'})
        }

class DiagnosticForm(forms.ModelForm):
    class Meta:
        model = Diagnostic
        fields = ['name', 'test_datetime', 'test_level']
        widgets = {
            'test_datetime': forms.DateTimeInput(attrs={'class': 'datetime-input'})
        }

project1/students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import  Student, Diagnostic
from .forms import StudentForm, DiagnosticForm

# Create your views here.

def index(request):
    students = Student.objects.all
    context = {'students': students}

    return render(request, 'students/index.html', context)



def create_student(request):
    form = StudentForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('students:index')

    return render(request, 'students/student-form.html',{'form': form})

def update_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    form = StudentForm(request.POST or None, instance=student)

    if form.is_valid():
        form.save()
        return redirect('students:index')

    return render(request, 'students/student-form.html', {'form': form, 'student': student})


def delete_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.method == 'POST':
        student.delete()
        return redirect('students:index')
    return render(request, 'students/stud-delete-confirm.html', {'student': student})

def diagnostics(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    diagnostics = student.diagnostic_set.get

    return render(request, 'diagnostics/diagnostics.html', {'student': student, 'diagnostics': diagnostics})

def create_diagnostic(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    form = DiagnosticForm(request.POST or None)

    if form.is_valid():
        diagnostic = form.save(commit=False)
        diagnostic.student = student
        diagnostic.save()
        return HttpResponseRedirect(reverse('students:diagnostics', args=(student.id,)))

    return render(request, 'diagnostics/diagnostic-form.html',{'student': student, 'form': form})


def update_diagnostic(request, student_id, diagnostic_id):
    student = get_object_or_404(Student, pk=student_id)
    diagnostic = get_object_or_404(Diagnostic, pk=diagnostic_id)
    form = DiagnosticForm(request.POST or None, instance=diagnostic)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('students:diagnostics', args=(student.id,)))

    return render(request, 'diagnostics/diagnostic-form.html', {'student': student, 'form': form, 'diagnostic': diagnostic})


def delete_diagnostic(request, student_id, diagnostic_id):
    student = get_object_or_404(Student, pk=student_id)
    diagnostic = get_object_or_404(Diagnostic, pk=diagnostic_id)
    if request.method == 'POST':
        diagnostic.delete()
        return HttpResponseRedirect(reverse('students:diagnostics', args=(student.id,)))
    return render(request, 'diagnostics/diag-delete-confirm.html', {'student': student, 'diagnostic': diagnostic})

project1/students/templates/diagnostics/diag-delete-confirm.html
{% load bootstrap %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <form method="post">
                {% csrf_token %}
                <h2>Are you sure to remove {{ diagnostic.name }}?</h2>
                <button type="submit" class="btn btn-danger">Sure!</button>
                <a href="{% url 'students:diagnostics' student.id %}" class="btn btn-default">Back</a>
            </form>
        </div>
    </div>

</body>
</html>

project1/students/templates/diagnostics/diagnostic-form.html
{% load bootstrap %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    <title>Diagnostic Form</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Diagnostic </h1>
            <form method="POST", role="form">
                {% csrf_token %}
                {{ form|bootstrap }}

                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{% url 'students:diagnostics' student.id %}" class="btn btn-default">Back</a>
            </form>
        </div>
    </div>
    <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
    </script>
</body>
</html>

project1/students/templates/diagnostics/diagnostics.html
{% load bootstrap %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Diagnostics</title>
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Diagnostics List</h1>
            <br>
            <a href="{% url 'students:create_diagnostic' student.id %}" class="btn btn-primary">Add Diagnostic</a>
            <br>
            <table class="table table-striped">

                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Test level</th>
                        <th>Test Date Time</th>
                        <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    {% for diagnostic in student.diagnostic_set.all %}
                    <tr>
                        <td>{{ diagnostic.name }}</td>
                        <td>{{ diagnostic.test_level }}</td>
                        <td>{{ diagnostic.test_datetime }}</td>
                        <td>
                            <a href="{% url 'students:update_diagnostic' student.id diagnostic.id %}" class="btn btn-primary">Edit</a>
                            <a href="{% url 'students:delete_diagnostic' student.id diagnostic.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="{% url 'students:index' %}" class="btn btn-default">Back</a>
        </div>
    </div>

</body>
</html>

project1/students/templates/students/index.html
{% load bootstrap %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    <title>Student List</title>
</head>
<body>
     <div class="container">
        <div class="row">
            <h1>Student List</h1>
            <br>
            <a href="{% url 'students:create_student' %}" class="btn btn-primary">Add student</a>
            <br>
            <table class="table table-striped">

                <thead>
                    <tr>
                        <th>Name</th>
                        <th>English Name</th>
                        <th>Gender</th>
                        <th>School</th>
                        <th>Grade</th>
                        <th>Birth</th>
                        <th>Diagnostic</th>
                        <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in students %}
                    <tr>
                        <td>{{ student.name }}</td>
                        <td>{{ student.name_en }}</td>
                        <td>{{ student.gender }}</td>
                        <td>{{ student.current_school_name}}</td>
                        <td>{{ student.current_school_grade}}</td>
                        <td>{{ student.birth_date }}</td>
                        <td>
                            <a href="{% url 'students:diagnostics' student.id %}" class="btn btn-default">Diagnostic</a>
                        </td>
                        <td>
                            <a href="{% url 'students:update_student' student.id %}" class="btn btn-primary">Edit Profile</a>
                            <a href="{% url 'students:delete_student' student.id %}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

project1/students/templates/students/stud-delete-confirm.html
{% load bootstrap %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete?</title>
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <form method="post">
        {% csrf_token %}
        <h2>Are you sure to remove {{ student.name }}?</h2>
        <button type="submit" class="btn btn-danger">Sure!</button>
        <a href="{% url 'students:index' %}" class="btn btn-default">Back</a>
    </form>
        </div>
    </div>

</body>
</html>

project1/students/templates/students/student-form.html
{% load bootstrap %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'students/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}"/>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
    <title>Student</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Student Profile</h1>
            <form method="POST", role="form">
                {% csrf_token %}
                {{ form|bootstrap }}
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="{% url 'students:index' %}" class="btn btn-default">Back</a>
            </form>
        </div>
    </div>
    <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD'
        });
    });
    </script>
</body>
</html>